name: Issue Month Statistics

on:
  repository_dispatch:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 1 1 * *"

jobs:
  month-statistics:
    runs-on: ubuntu-latest
    steps:
      - name: month-statistics
        uses: actions-cool/issues-month-statistics@v1
        with:
          count-lables: true
          count-comments: true
          emoji: 'eyes'