name: release_docker_amd64

on:
  repository_dispatch:
  workflow_dispatch:
#  push:
#    branches:
#      - 'v2'
#    tags:
#      - 'v*'
#  pull_request:
#    branches:
#      - 'v2'

jobs:
  docker_release:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: xinb/alist
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build web
        run: |
          git clone -b dist https://github.com/xopenwrt/alist-web.git
          mv alist-web/* public
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: xinb
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64